package com.aarohan.claims.model;

public enum ValidationErrorCode {
    MISSING_CLAIM_ID,
    MISSING_MEMBER_ID,
    MISSING_PROVIDER_NPI,
    MISSING_STATUS,
    MISSING_SERVICE_DATE,
    MISSING_BILLED_AMOUNT,

    MEMBER_NOT_FOUND,

    MEMBER_INACTIVE,
    PROVIDER_NOT_FOUND,
    PROVIDER_OUT_OF_NETWORK,
    SERVICE_DATE_INVALID,
    BILLED_AMOUNT_INVALID,
    DIAGNOSIS_CODE_INVALID,
}
